'use client'
import React from 'react'
import { Image, Accordion, Grid, Container, Title } from "@mantine/core"
// import image from "./image.svg"
import classes from "./faq.module.css"

const Faq = () => {
    return (
        <div className={classes.wrapper}>
            <Container size="lg">
                <Grid id="faq-grid" gutter={50}>
                    <Grid.Col span={{ base: 12, md: 6 }}>
                        {/* <Image src={image.src} alt="Frequently Asked Questions" /> */}
                    </Grid.Col>
                    <Grid.Col span={{ base: 12, md: 6 }}>
                        <Title order={2} ta="left" className={classes.title}>
                            Tour Generator FAQ's
                        </Title>

                        <Accordion
                            chevronPosition="right"
                            defaultValue="reset-password"
                            variant="separated"
                        >
                            <Accordion.Item className={classes.item} value="reset-password">
                                <Accordion.Control>
                                    What is the Tour Generator and how does it work?
                                </Accordion.Control>
                                <Accordion.Panel>The Tour Generator is a feature that allows users to create personalized website tours, guiding them through key sections of any website based on their preferences.</Accordion.Panel>
                            </Accordion.Item>

                            <Accordion.Item className={classes.item} value="another-account">
                                <Accordion.Control>
                                    Can I customize the content and settings of the tours generated by the Tour Generator?

                                </Accordion.Control>
                                <Accordion.Panel>Yes, the Tour Generator offers extensive customization options, allowing users to select specific sections, set tour preferences, and personalize the tour experience according to their interests.</Accordion.Panel>
                            </Accordion.Item>

                            <Accordion.Item className={classes.item} value="newsletter">
                                <Accordion.Control>
                                    Is the Tour Generator compatible with all types of websites?
                                </Accordion.Control>
                                <Accordion.Panel>The Tour Generator is designed to work with most websites, but compatibility may vary depending on the website's structure and content. We continuously strive to improve compatibility to ensure a seamless experience for users.
                                </Accordion.Panel>
                            </Accordion.Item>

                            <Accordion.Item className={classes.item} value="credit-card">
                                <Accordion.Control>
                                    Can I share the tours generated by the Tour Generator with others?
                                </Accordion.Control>
                                <Accordion.Panel>Yes, users can save their customized tours and share them with others through various channels, such as email, social media, or direct links.</Accordion.Panel>
                            </Accordion.Item>

                            <Accordion.Item className={classes.item} value="credit-card">
                                <Accordion.Control>
                                    Are there any limitations on the number of tours I can create using the Tour Generator?
                                </Accordion.Control>
                                <Accordion.Panel>There are no limitations on the number of tours users can create using the Tour Generator. Users can create as many tours as they need for their website exploration purposes.</Accordion.Panel>
                            </Accordion.Item>
                        </Accordion>
                    </Grid.Col>
                </Grid>
            </Container>
        </div >
    )
}

export default Faq