import { Inter } from "next/font/google";
import "./globals.css";
import { MantineProvider, createTheme } from "@mantine/core";
import '@mantine/core/styles.css';
import Navbar from './(main)/navbar';
import { Footer } from "./(main)/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VoiceTour Navigator",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */

});

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <MantineProvider theme={theme} defaultColorScheme="dark">
        <div style={{backgroundColor:'#1b191b'}}>
          {children}
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
